spring:
 cloud:
   gateway:
     globalcors:
       corsConfigurations:
         '[/**]':
           allowedOrigins: "http://localhost:3000"  # Buraya izin verilen origin URL'lerini ekleyin
           allowedMethods:
             - GET
             - POST
           allowedHeaders:
             - "*"
           allowCredentials: true
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter

       - id: AdService
         uri: lb://ADSERVICE
         predicates:
           - Path=/api/v1/ads/**
         filters:
           - AuthenticationFilter

       - id: PackageService
         uri: lb://PACKAGESERVICE
         predicates:
           - Path=/api/v1/packages/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**

       - id: PaymentService
         uri: lb://PAYMENTSERVICE
         predicates:
           - Path= /api/v1/payments/**
         filters:
           - AuthenticationFilter

       - id: UserService
         uri: lb://USERSERVICE
         predicates:
           - Path=/api/v1/user/**
         filters:
           - AuthenticationFilter

 application:
   name: SWIGGY-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/